from __future__ import annotations

import json
from pathlib import Path


HEADER = "# AUTO-GENERATED, DO NOT EDIT\n"
GENERATOR_NOTE = "# Generated by advArchiver/scripts/build_single_file.py\n"


def module_name_for(relative_path: Path) -> str:
    parts = ["advArchiver", "advArchiver", *relative_path.parts]
    if parts[-1] == "__init__.py":
        return ".".join(parts[:-1])
    parts[-1] = relative_path.stem
    return ".".join(parts)


def read_module_sources(
    source_root: Path,
) -> tuple[dict[str, str], list[str], dict[str, str]]:
    module_sources = {"advArchiver": ""}
    package_names = {"advArchiver"}
    module_files = {"advArchiver": "<generated:advArchiver>"}

    for source_path in sorted(source_root.rglob("*.py")):
        relative_path = source_path.relative_to(source_root)
        module_name = module_name_for(relative_path)
        module_sources[module_name] = source_path.read_text(encoding="utf-8")
        module_files[module_name] = relative_path.as_posix()
        if relative_path.name == "__init__.py":
            package_names.add(module_name)

    return module_sources, sorted(package_names), module_files


def render_output(
    module_sources: dict[str, str],
    package_names: list[str],
    module_files: dict[str, str],
) -> str:
    sources_literal = json.dumps(module_sources, indent=2, sort_keys=True)
    packages_literal = json.dumps(package_names, indent=2)
    files_literal = json.dumps(module_files, indent=2, sort_keys=True)
    return (
        HEADER
        + GENERATOR_NOTE
        + "\n"
        + "from __future__ import annotations\n\n"
        + "import importlib.abc\n"
        + "import importlib.util\n"
        + "import sys\n\n"
        + f"PACKAGE_NAMES = {packages_literal}\n\n"
        + f"MODULE_FILES = {files_literal}\n\n"
        + f"MODULE_SOURCES = {sources_literal}\n\n"
        + "\n"
        + "class _EmbeddedModuleFinder(importlib.abc.MetaPathFinder, importlib.abc.Loader):\n"
        + "    def find_spec(self, fullname, path=None, target=None):\n"
        + "        del path, target\n"
        + "        if fullname not in MODULE_SOURCES:\n"
        + "            return None\n"
        + "        return importlib.util.spec_from_loader(\n"
        + "            fullname,\n"
        + "            self,\n"
        + "            is_package=fullname in PACKAGE_NAMES,\n"
        + "        )\n\n"
        + "    def create_module(self, spec):\n"
        + "        del spec\n"
        + "        return None\n\n"
        + "    def exec_module(self, module):\n"
        + '        filename = MODULE_FILES.get(module.__name__, f"<generated:{module.__name__}>")\n'
        + "        if module.__spec__ is not None and module.__spec__.submodule_search_locations is not None:\n"
        + "            module.__path__ = []\n"
        + "        module.__file__ = filename\n"
        + "        source = MODULE_SOURCES[module.__name__]\n"
        + '        code = compile(source, filename, "exec")\n'
        + "        exec(code, module.__dict__)\n\n"
        + "\n"
        + "if not any(isinstance(finder, _EmbeddedModuleFinder) for finder in sys.meta_path):\n"
        + "    sys.meta_path.insert(0, _EmbeddedModuleFinder())\n\n"
        + "from advArchiver.advArchiver.cli import main\n\n"
        + 'if __name__ == "__main__":\n'
        + "    raise SystemExit(main())\n"
    )


def main() -> int:
    script_path = Path(__file__).resolve()
    worktree_root = script_path.parents[2]
    advarchiver_root = worktree_root / "advArchiver"
    source_root = advarchiver_root / "advArchiver"
    dist_path = advarchiver_root / "dist" / "advArchiver.py"

    module_sources, package_names, module_files = read_module_sources(source_root)
    output_text = render_output(module_sources, package_names, module_files)

    dist_path.parent.mkdir(parents=True, exist_ok=True)
    dist_path.write_text(output_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
